Iter1
MihailSergeenkov/gophermart pull request #1
Opened 2024-07-16 07:23 UTC by MihailSergeenkov

2024-07-25 07:35 UTC, s-shpak requested changes

2024-07-25 07:35 UTC, s-shpak commented on compose.yaml
> +      - "5434:5432"
`HOST_PORT` совпадает с портом контейнера `db_gophermart`

2024-07-25 07:35 UTC, s-shpak commented on internal/app/clients/accrual.go
> +	requestTimeout   = 1  // in seconds
1. Кажется, что таймаут очень маленький
2. Эти и подобные параметры лучше делать конфигурируемыми

2024-07-25 07:35 UTC, s-shpak commented on internal/app/clients/accrual.go
> +func newAccrualClient(settings *config.Settings, logger *zap.Logger) *AccrualClient {
Клиенту необходимы все парамметры из `settings` ?

2024-07-25 07:35 UTC, s-shpak commented on internal/app/clients/accrual.go
> +		ac.logger.Error("failed to construct URL", zap.Error(err))
Зачем логировать ошибку, если она возвращается из этого метода ?

2024-07-25 07:35 UTC, s-shpak commented on internal/app/clients/accrual.go
> +		return newToManyRequestsError(baseRetryTimeout)
А вот здесь ошибку парсинга как раз можно залогировать, т.к. иначе она потеряется

2024-07-25 07:35 UTC, s-shpak commented on internal/app/clients/clients.go
> +type Clients struct {
Почему `Clients`, если клиент один ?

2024-07-25 07:35 UTC, s-shpak commented on internal/app/common/common.go
Это считается антипаттерном: сущности внтури этого пакета никак не связаны, разнеси их по тем пакетам, где они используются. Кажется, что все эти сущности используются на уровне получения запроса и отправки ответа

2024-07-25 07:35 UTC, s-shpak commented on internal/app/config/config.go
> +	flag.StringVar(&s.RunAddr, "a", s.RunAddr, "address and port to run server")
Такой подход перепишет значения переменных окружений дефолтными значениями флагов

2024-07-25 07:35 UTC, s-shpak commented on internal/app/data/data.go
> +type Storager interface {
Зачем создавать этот интрефейс ?

2024-07-25 07:35 UTC, s-shpak commented on internal/app/data/db.go
> +	_ "github.com/jackc/pgx/v5/stdlib"
Это зачем ?

2024-07-25 07:35 UTC, s-shpak commented on internal/app/data/migrations/00001_init.up.sql
> +	password VARCHAR(300) NOT NULL
Почему бы не хранить это поле в байтах?

2024-07-25 07:35 UTC, s-shpak commented on internal/app/services/balances_test.go
> +func TestSuccessGetBalance(t *testing.T) {
Лучше использовать table driven tests

2024-07-25 07:35 UTC, s-shpak commented on internal/app/services/services.go
> +		return ErrOrderNumberValidation
В ошибке стоит возвращать значение (и другой необходимый контекст), которое к ней привело

2024-07-25 07:35 UTC, s-shpak commented on internal/app/services/users.go
> +const uniqueConstraintCode = "23505"
Используй лучше https://github.com/jackc/pgerrcode

2024-07-25 07:35 UTC, s-shpak commented on internal/app/jobs/orders.go
> +const processOrderAccrualWorkers = 3
Это должно быть параметризуемым

2024-07-25 07:35 UTC, s-shpak commented on internal/app/jobs/orders.go
> +			ordersCh := generator(stopCh, orders)
1. Зачем на каждый тик генерировать новый канал ?
2. Если канал будет заполнен, и придет `Too many requests`, то воркеры продолжат работу, что неправильно

2024-07-30 08:35 UTC, s-shpak commented on internal/app/config/config.go
> +	flag.StringVar(&s.RunAddr, "a", s.RunAddr, "address and port to run server")
Здесь не поправлено

2024-07-30 08:35 UTC, s-shpak commented on internal/app/data/data.go
> +type Storager interface {
Вопрос открыт

2024-07-30 08:35 UTC, s-shpak commented on internal/app/data/migrations/00001_init.up.sql
> +	password VARCHAR(300) NOT NULL
Вопрос открыт

2024-07-30 08:35 UTC, s-shpak commented on internal/app/services/balances_test.go
> +func TestSuccessGetBalance(t *testing.T) {
Что с этим ?

2024-07-30 08:35 UTC, s-shpak commented on internal/app/jobs/orders.go
> +			ordersCh := generator(stopCh, orders)
Сейчас реализация кажется неправильной.

У тебя должен быть пул воркеров. На каждый тик диспетчер должен идти в БД, доставать необработанные заказы и передавать их в очередь задач. Воркеры должны читать эту очередь. Если от аккруала приходит 429 воркеры должны останавливаться (как и диспетчер) и ожидать переданного интервала времени для продолжения работы

2024-07-30 08:36 UTC, s-shpak requested changes
См. старые и новые комментарии. Выдай мне, пожалуйста, права контрибьютера еще раз, чтобы я мог закрыть решенные комментарии

2024-07-30 09:02 UTC, MihailSergeenkov commented
Ответил на вопросы, доступ предоставил.

2024-07-30 09:43 UTC, MihailSergeenkov commented on internal/app/clients/clients.go
> +type Clients struct {
Сейчас один, потом добавится еще один, если живем в парадигме agile, то это норма. Если коробочное решение, то не норма. Оставлю, как есть.

2024-07-30 09:43 UTC, MihailSergeenkov commented on internal/app/data/data.go
> +type Storager interface {
Чтобы была возможность быстрой замены БД. Для тестируемости, для отделения логики БД от бизнес логики.

2024-07-30 09:43 UTC, MihailSergeenkov commented on internal/app/data/migrations/00001_init.up.sql
> +	password VARCHAR(300) NOT NULL
Если вопрос есть, то конечно, какой-то смысл может быть. Как понимаю, это отсутствие необходимости конвертации в коде. За безопастность ничего не вижу. Но я бы оставил строку, тк при изменении языка программирования на такие как Ruby или Python, будут проблемы. Поле в байтах, эта история специфичная для языков более низкого уровня. Т.е. таким образом специфика языка просачивается в БД.

2024-07-30 09:43 UTC, MihailSergeenkov commented on internal/app/services/balances_test.go
> +func TestSuccessGetBalance(t *testing.T) {
Использую, но в данном тесте вижу от него больше сложности чтения, чем выгод.
Наличие if-ов в теле теста (особенно с моками), так себе для чтения.

2024-07-30 09:43 UTC, MihailSergeenkov commented on internal/app/clients/accrual.go
> +	requestTimeout   = 1  // in seconds
То, что он должен быть конфигурируемым, согласен. А то, что 1 очень мало, это субъективно. Нужно видеть статистику, чтобы сказать точно.

2024-07-30 09:43 UTC, MihailSergeenkov commented on compose.yaml
> +      - "5434:5432"
разве? там 5433, а здесь 5434.

2024-07-30 09:43 UTC, MihailSergeenkov commented on internal/app/clients/accrual.go
> +func newAccrualClient(settings *config.Settings, logger *zap.Logger) *AccrualClient {
Не все, но не хотелось бы переписывать инициализатор каждый раз при добавлении новой настройки.
В структуре клиента для Accrual убрал хранение всех параметров, оставил только адрес.

2024-07-30 09:43 UTC, MihailSergeenkov commented on internal/app/config/config.go
> +	flag.StringVar(&s.RunAddr, "a", s.RunAddr, "address and port to run server")
<img width="1418" alt="image" src="https://github.com/user-attachments/assets/7b651e6c-355e-498e-808c-68916c41b517">

2024-07-30 09:43 UTC, MihailSergeenkov commented on internal/app/data/db.go
> +	_ "github.com/jackc/pgx/v5/stdlib"
Убрал, мусор.

2024-07-30 09:43 UTC, MihailSergeenkov commented on internal/app/clients/accrual.go
> +		ac.logger.Error("failed to construct URL", zap.Error(err))
убрал

2024-07-30 09:43 UTC, MihailSergeenkov commented on internal/app/clients/accrual.go
> +		return newToManyRequestsError(baseRetryTimeout)
Добавил

2024-07-30 09:43 UTC, MihailSergeenkov commented on internal/app/common/common.go
Только пару сущностей использовалось только в хендлерах, остальные еще и в других пакетах.
Сущность связанная с контекстом используется еще и на уровне БД. 
Все кроме нее разнес, эту оставил, может быть common не самое подходящее название. Но назвать пакет context будет тоже плохо, тк будет постоянный конфликт с стандартной библиотекой.

2024-07-30 09:43 UTC, MihailSergeenkov commented on internal/app/services/services.go
> +		return ErrOrderNumberValidation
Поправил

2024-07-30 09:43 UTC, MihailSergeenkov commented on internal/app/services/users.go
> +const uniqueConstraintCode = "23505"
Сделал

2024-07-30 09:43 UTC, MihailSergeenkov commented on internal/app/jobs/orders.go
> +const processOrderAccrualWorkers = 3
Сделал

2024-07-30 09:43 UTC, MihailSergeenkov commented on internal/app/jobs/orders.go
> +			ordersCh := generator(stopCh, orders)
Переделал

2024-07-30 09:43 UTC, MihailSergeenkov commented on internal/app/clients/accrual.go
> +	requestTimeout   = 1  // in seconds
Таймаут добавил в конфиг

2024-07-30 09:43 UTC, MihailSergeenkov commented on internal/app/config/config.go
> +	flag.StringVar(&s.RunAddr, "a", s.RunAddr, "address and port to run server")
На скриншоте показал, что все работает как надо.

2024-07-30 09:43 UTC, MihailSergeenkov commented on internal/app/data/data.go
> +type Storager interface {
В комментарии указал почему сделал именно так.

2024-07-30 09:43 UTC, MihailSergeenkov commented on internal/app/data/migrations/00001_init.up.sql
> +	password VARCHAR(300) NOT NULL
В комментарии указал почему сделал именно так.

2024-07-30 09:43 UTC, MihailSergeenkov commented on internal/app/services/balances_test.go
> +func TestSuccessGetBalance(t *testing.T) {
В комментарии указал почему сделал именно так.

2024-07-30 09:43 UTC, MihailSergeenkov commented on internal/app/jobs/orders.go
> +			ordersCh := generator(stopCh, orders)
Почему неправильной? Когда все так и делается, кроме того, что я вообще пропускаю тик, если у нас 429 ошибка. Тем самым убираю лишний запрос к БД.

2024-08-01 11:58 UTC, s-shpak commented on internal/app/data/migrations/00001_init.up.sql
> +	password VARCHAR(300) NOT NULL
Какого рода проблемы останутся при перезоде на другой высокоуровневый язык ? Python и Ruby не работают с байтами ?

2024-08-01 11:59 UTC, s-shpak commented on internal/app/clients/accrual.go
> +func newAccrualClient(settings *config.Settings, logger *zap.Logger) *AccrualClient {
Как именно будет меняться инициализатор, если в него передавать специфичный для `accrual` объект конфигурации ?

2024-08-01 12:00 UTC, s-shpak commented on internal/app/clients/clients.go
> +type Clients struct {
God-like объекты это плохо. Впрочем, этот комментарий можно зарезолвить, если ты не хочешь менять код здесь

2024-08-01 12:02 UTC, s-shpak commented on internal/app/data/data.go
> +type Storager interface {
Ни один из аргументов не валиден:
1. Как такой подход помогает проще тестировать приложение ? Моки объявляются на уровне, где используется хранилище. Там и нужно объявлять интерфейс
2. Про отделение вообще не понял

Золотое правило Го (которое можно нарушать, но когда знаешь, что делаешь): возвращай стуктуру, принимай на вход интерфейс

2024-08-01 12:16 UTC, s-shpak requested changes

2024-08-01 12:16 UTC, s-shpak commented on internal/app/jobs/orders.go
> +			ordersCh := generator(stopCh, orders)
По следующим причинам:
1. Сейчас диспетчер ожидает в режиме `spin-lock`
2. Воркер теряет любые другие ошибки, кроме `TooManyRequests`
3. `TooManyRequests` приведет к остановке максимум одного воркера (см. строку 54)
4. Сейчас количетво запускаемых горутин не равно количеству воркеров: внутри функции `worker` для каждого нового `order` запускается новая горутина (см. строку 90)

Кроме того кажется, что запускать вокер-пул на каждый тик не очень правильно.

2024-08-01 12:16 UTC, s-shpak commented on internal/app/jobs/orders.go
> +		case <-ctx.Done():
Желательно приоритизировать выполнение этой ветви, чтобы если контекст был завершен, то при вызове select гарантировано происходил бы выход из функции

2024-08-04 13:37 UTC, MihailSergeenkov commented on internal/app/clients/accrual.go
> +func newAccrualClient(settings *config.Settings, logger *zap.Logger) *AccrualClient {
Переделал на специфичный для accrual объект конфигурации. env все-таки умеет работать с подструктурами. в доке про это очень скудно написано(

2024-08-04 13:38 UTC, MihailSergeenkov commented on internal/app/clients/clients.go
> +type Clients struct {
Обсудили на 1 на 1. Убрал.

2024-08-04 13:39 UTC, MihailSergeenkov commented on internal/app/data/data.go
> +type Storager interface {
Обсудили на 1 на 1. Передал на работу без интерфейса, интерфейсы объявил на уровне потребителей БД.

2024-08-04 13:40 UTC, MihailSergeenkov commented on internal/app/data/migrations/00001_init.up.sql
> +	password VARCHAR(300) NOT NULL
Также обсудили на 1 на 1. Ради интереса сделал через хранения в байтах.

2024-08-04 13:40 UTC, MihailSergeenkov commented on internal/app/jobs/orders.go
> +		case <-ctx.Done():
Сделал

2024-08-04 13:44 UTC, MihailSergeenkov commented on internal/app/jobs/orders.go
> +			ordersCh := generator(stopCh, orders)
После обсуждения на 1 на 1.
1. оставили без изменений
2. стал логировать остальные ошибки
3. остановку переделал на засыпание
4. тоже переделал
5. воркеры и очередь с ордерами вынес из обработки тика

Реализацию протестировал в ручную. Работает, как задумано.

2024-08-05 11:15 UTC, s-shpak approved these changes

2024-08-05 11:52 UTC, merged